### ISSUE TITLE
segfault when declare cyclic type

### ISSUE THREAD

**Issue by DeaDDooMER** [vishaps/voc#60]
I write my own oberon compiler and check some behaviors in another compilers.
In voc cyclic types checked not fully. :)

```
MODULE Test;

TYPE
        MyArr = POINTER TO ARRAY OF MyArr;

END Test.
```

```
$ voc Test.Mod -m
Segmentation fault (core dumped)
```

**Comment by norayr** [comment]
very interesting, thank you for reporting.

i'll allocate time for this in nearest days.

**Comment by norayr** [comment]
https://github.com/vishaps/voc/commit/511186f0a42727b8439ca8e986de8063e6342f9d

forgot to close the issue. (:
