### ISSUE TITLE
POSIX Makefile or separate BSD Makefile

### ISSUE THREAD

**Issue by antranigv** [vishaps/voc#63]
as someone who runs voc on FreeBSD, I have a huge issue that I must have gmake in order to compile it. I might suggest two things.

either 1) port current GNU Makefile to POSIX Makefile or 2) write a separate BSD Makefile (Makefile.bsd?) with BSD Make syntax. This will also make porting voc to *BSD ports easier.

what do you guys think?

**Comment by dcwbrown** [comment]
It is supposed to work fine with BSD's make. I spent a lot of time making the makefile work on both GNU and BSD make!
Indeed it builds fine on my test machines.

**Comment by dcwbrown** [comment]
Hi Antranig, did you get anywhere with this? Have you been able to build on FreeBSD without gmake?

**Comment by antranigv** [comment]
sorry for my late reply.
due to some special configuration on my own system, this was a mistake, it's working amazing on a base FreeBSD system without any external makes or compilers.

Thanks a lot for understanding!
