### ISSUE TITLE
libvoc-02.so not found after make full

### ISSUE THREAD

**Issue by MarcusE1W** [vishaps/voc#95]
Hi

I have installed voc successfully on a PinebookPro (aarch64) with Armbian (Ubuntu).

If I use clang all went well and the tests passed.

However, when I compiled the hello test prog in a different folder it compiled fine, but then did not run. For `./hello` I get the error:

```
./hello: error while loading shared libraries: libvoc-O2.so: cannot open shared object file: No such file or directory
```

`make install` solved the issue.

**Comment by norayr** [comment]
thank you!

i think somehow ldconfig step failed, but i don't know how.
you can see there should be libvoc.conf in /etc/ld.so.conf.d directory.
it should contain something like `/opt/voc/lib` or other path - depending on your installation.

and then ldconfig should be run during the installation process. it is interesting why it failed.
i had different issue on pinebook: https://github.com/vishaps/voc/issues/84
