### ISSUE TITLE
Make does not properly uninstall: typo in variable name

### ISSUE THREAD

**Issue by vgratian** [vishaps/voc#97]
In [src/tools/make/oberon.mk#L193](https://github.com/vishaps/voc/blob/8bd5388ffb562952b5c62200e46c10ffb1f92bc2/src/tools/make/oberon.mk#L193):

```makefile
@sh src/tools/make/addlibrary.sh uninstall "$(INSTALLDIR)/lib" $(oname)
```

`$(oname)` should be `$(ONAME)` (make is [case-sensitive](https://www.gnu.org/software/make/manual/html_node/Using-Variables.html)).

Because of this typo, when you run `make uninstall`, make does not remove  `/etc/ld.so.conf.d/libvoc.conf`, instead, it [tries](https://github.com/vishaps/voc/blob/8bd5388ffb562952b5c62200e46c10ffb1f92bc2/src/tools/make/addlibrary.sh#L17) to remove `/etc/ld.so.conf.d/lib.conf`.

**Comment by norayr** [comment]
fixed, thank you for noticing!
